[package]
name = "libm8gd"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.4.5", features = ["register-docs"] }
libm8 = { version = "0.1.0", path = "../libm8" }
