[package]
name = "libm8"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0.17.0", features = ["build-from-source-static"] }
serialport = "4.8.1"
spectrum-analyzer = "1.7.0"
thiserror = "2.0.17"
